baseURL = 'https://www.tatsatbanerjee.in/'
languageCode = 'en-us'
title = 'Tatsat Banerjee | Personal Homepage'
theme = "TatBanTheme2.0"
disqusShortname = 'tatsatb'



[taxonomies]
  category = 'categories'
  tag = 'tags'




[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Gorritos de fiesta"
    url = "/gorritos-de-fiesta/"
    weight = 2
  [[menu.main]]
    name = "Publicationes"
    url = "/publication/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
    
[module]
  [module.hugoVersion]
    extended = true
    min = "0.60.0"
    max = "0.97.0"   
